# Generated by Django 4.2.6 on 2023-10-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_rename_birth_date_teacher_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.CharField(max_length=50),
        ),
    ]
